name: Build RustDesk (Windows + Android)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    name: 🪟 Build Windows GUI
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment variables
        run: |
          echo "RUSTDESK_RELAY=$env:RELAY_SERVER" | Out-File -FilePath .env -Encoding utf8 -Append
          echo "RUSTDESK_RENDEZVOUS=$env:RENDEZVOUS_SERVER" | Out-File -FilePath .env -Encoding utf8 -Append
          echo "RUSTDESK_KEY=$env:ENCRYPT_KEY" | Out-File -FilePath .env -Encoding utf8 -Append
        env:
          RELAY_SERVER: ${{ secrets.RELAY_SERVER }}
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      - name: Install Python
        run: |
          choco install python --version=3.10.11 -y
          python --version


      - name: Build Windows release
        run: |
          python build.py --flutter --portable

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: dist/
