name: Build RustDesk (Windows + Android)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Configure custom servers
        run: |
          echo "RUSTDESK_RELAY=$env:RELAY_SERVER" | Out-File -FilePath .env -Encoding utf8 -Append
          echo "RUSTDESK_RENDEZVOUS=$env:RENDEZVOUS_SERVER" | Out-File -FilePath .env -Encoding utf8 -Append
          echo "RUSTDESK_KEY=$env:ENCRYPT_KEY" | Out-File -FilePath .env -Encoding utf8 -Append
        env:
          RELAY_SERVER: ${{ secrets.RELAY_SERVER }}
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      - name: Build Windows binary
        run: |
          cargo build --release --features gui

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: target/release/rustdesk.exe

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl unzip python3

      - name: Install Flutter & Android SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Configure environment variables
        run: |
          echo "RUSTDESK_RELAY=${{ secrets.RELAY_SERVER }}" >> .env
          echo "RUSTDESK_RENDEZVOUS=${{ secrets.RENDEZVOUS_SERVER }}" >> .env
          echo "RUSTDESK_KEY=${{ secrets.ENCRYPT_KEY }}" >> .env

      - name: Build Android APK
        run: |
          cd flutter
          flutter build apk --release

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-android
          path: flutter/build/app/outputs/flutter-apk/app-release.apk
