name: Build RustDesk Windows x64 (Sciter) with custom server ID & key

on:
  push:
    branches: [ main, master ]
    paths:
      - '.github/workflows/'
      - '/.rs'
      - 'Cargo.'
      - 'libs/'
      - 'src/'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

env:
  # Default values (use GitHub Secrets instead for production).
  DEFAULT_RENDEZVOUS_SERVER: example.yourdomain.tld
  DEFAULT_RS_PUB_KEY: "REPLACE_WITH_BASE64_PUBLIC_KEY"
  DEFAULT_RELAY_SERVER: ""

jobs:
  build-windows-x64:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout (submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter Windows desktop
        run: |
          flutter config --enable-windows-desktop
          flutter --version
          flutter doctor -v

      - name: Install LLVM/Clang (for bindgen)
        run: |
          choco install -y llvm --version=15.0.2
          echo "LIBCLANG_PATH=C:\\Program Files\\LLVM\\bin" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install Git & vcpkg dependencies
        run: |
          git --version
          git clone https://github.com/microsoft/vcpkg $env:USERPROFILE\vcpkg
          & $env:USERPROFILE\vcpkg\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=$env:USERPROFILE\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append
          $pkgs = @('libvpx:x64-windows-static','libyuv:x64-windows-static','opus:x64-windows-static','aom:x64-windows-static')
          & $env:USERPROFILE\vcpkg\vcpkg.exe install $pkgs

      - name: Cache cargo registry + git
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache vcpkg installed
        uses: actions/cache@v4
        with:
          path: ${{ env.USERPROFILE }}\vcpkg\installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('.github/workflows/**','vcpkg.json') }}

      - name: Download Sciter DLL (RustDesk Windows desktop)
        run: |
          New-Item -ItemType Directory -Force -Path target\release | Out-Null
          Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.win/x64/sciter.dll -OutFile target\release\sciter.dll

      - name: (Optional) Set ID/Key/Relay from Secrets
        env:
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
          RELAY_SERVER: ${{ secrets.RELAY_SERVER }}
        run: |
          if (-not $env:RENDEZVOUS_SERVER) { $env:RENDEZVOUS_SERVER = "$env:DEFAULT_RENDEZVOUS_SERVER" }
          if (-not $env:RS_PUB_KEY) { $env:RS_PUB_KEY = "$env:DEFAULT_RS_PUB_KEY" }
          if (-not $env:RELAY_SERVER) { $env:RELAY_SERVER = "$env:DEFAULT_RELAY_SERVER" }
          echo "Using RENDEZVOUS_SERVER=$env:RENDEZVOUS_SERVER"
          echo "Using RS_PUB_KEY=(hidden)"
          echo "Using RELAY_SERVER=$env:RELAY_SERVER"
          $candidateFiles = Get-ChildItem -Recurse -File -Path libs -Filter config.rs
          if ($candidateFiles.Count -eq 0) {
            Write-Error "config.rs not found: repo structure changed?"; exit 1
          }
          foreach ($f in $candidateFiles) {
            (Get-Content $f.FullName) | 
              ForEach-Object {
                $_ -replace '(?m)^(\s*pub\s+const\s+DEFAULT_RENDEZVOUS_SERVER\s*:\s*&str\s*=\s*)"[^"]*"', "$1\"$env:RENDEZVOUS_SERVER\"" |
                ForEach-Object { $_ -replace '(?m)^(\s*pub\s+const\s+DEFAULT_RS_PUB_KEY\s*:\s*&str\s*=\s*)"[^"]*"', "$1\"$env:RS_PUB_KEY\"" } |
                ForEach-Object { $_ -replace '(?m)^(\s*pub\s+const\s+DEFAULT_RELAY_SERVER\s*:\s*&str\s*=\s*)"[^"]*"', "$1\"$env:RELAY_SERVER\"" }
              } | Set-Content $f.FullName -Encoding UTF8
          }

      - name: Build (release, x64)
        env:
          VCPKG_ROOT: ${{ env.VCPKG_ROOT }}
        run: |
          $env:VCPKG_ROOT = "$env:VCPKG_ROOT"
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Rename binary with host/key (optional)
        env:
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER || env.DEFAULT_RENDEZVOUS_SERVER }}
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY || env.DEFAULT_RS_PUB_KEY }}
        run: |
          $exePath = Join-Path (Resolve-Path target\x86_64-pc-windows-msvc\release).Path 'rustdesk.exe'
          if (Test-Path $exePath) {
            $safeHost = ($env:RENDEZVOUS_SERVER -replace '[^a-zA-Z0-9.-]', '-')
            $out = "rustdesk-host=$safeHost,key=hidden.exe"
            Copy-Item $exePath $out
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-x64
          path: |
            target\x86_64-pc-windows-msvc\release\rustdesk.exe
            rustdesk-host=*.exe
            target\release\sciter.dll

      - name: Show binary size
        run: |
          Get-ChildItem target\x86_64-pc-windows-msvc\release\rustdesk.exe | Select-Object Name,Length
